apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: audiounits.app.paradise.dev
spec:
  group: app.paradise.dev
  names:
    kind: AudioUnit
    listKind: AudioUnitList
    plural: audiounits
    singular: audiounit
    shortNames:
      - au
      - aus
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AudioUnit is the Schema for the audiounits API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AudioUnitSpec defines the desired state of AudioUnit
          type: object
        status:
          description: AudioUnitStatus defines the observed state of AudioUnit
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
