[workspace]
default-members = [
  "types",
  "controller",
  "daemon",
  "paradise",
   "vst2",
   "vst3",
   "tool",
]
members = [
  "types",
  "controller",
  "daemon",
  "paradise",
  "vst2",
  "vst3",
  "tool",
]
