[workspace]
default-members = [
  "types",
  "core",
  "operator",
  "daemon",
   "vst2",
   "vst3",
   "tool",
]
members = [
  "types",
  "core",
  "operator",
  "daemon",
  "vst2",
  "vst3",
  "tool",
]
