// Code generated by oto; DO NOT EDIT.

pub trait AudioInterface: Send + Sync {
    fn create_stream(&self, req: CreateStreamRequest) -> Result<CreateStreamResponse, String>;
    fn delete_stream(&self, req: DeleteStreamRequest) -> Result<DeleteStreamResponse, String>;
    fn get_device_info(&self, req: GetDeviceInfoRequest) -> Result<GetDeviceInfoResponse, String>;
    fn list_streams(&self, req: ListStreamsRequest) -> Result<ListStreamsResponse, String>;
}

#[derive(Serialize, Deserialize)]
pub struct Address {
    pub host: String,
    pub port: i64,
}

impl Address {
    pub fn new() -> Self {
        Address {
            host: Default::default(),
            port: Default::default(),
        }
    }

    pub fn make(host: String, port: i64) -> Self {
        Address { host, port }
    }
}

impl Default for Address {
    fn default() -> Address {
        Address::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct HardwarePort {
    pub channel: i64,
    pub sample_rate: i64,
    pub sample_format: String,
}

impl HardwarePort {
    pub fn new() -> Self {
        HardwarePort {
            channel: Default::default(),
            sample_rate: Default::default(),
            sample_format: Default::default(),
        }
    }

    pub fn make(channel: i64, sample_rate: i64, sample_format: String) -> Self {
        HardwarePort {
            channel,

            sample_rate,

            sample_format,
        }
    }
}

impl Default for HardwarePort {
    fn default() -> HardwarePort {
        HardwarePort::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct Stream {
    pub name: String,
    pub is_output: bool,
    pub address: Address,
    pub hardware_port: HardwarePort,
}

impl Stream {
    pub fn new() -> Self {
        Stream {
            name: Default::default(),
            is_output: Default::default(),
            address: Default::default(),
            hardware_port: Default::default(),
        }
    }

    pub fn make(
        name: String,
        is_output: bool,
        address: Address,
        hardware_port: HardwarePort,
    ) -> Self {
        Stream {
            name,

            is_output,

            address,

            hardware_port,
        }
    }
}

impl Default for Stream {
    fn default() -> Stream {
        Stream::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct CreateStreamRequest {
    pub stream: Stream,
}

impl CreateStreamRequest {
    pub fn new() -> Self {
        CreateStreamRequest {
            stream: Default::default(),
        }
    }

    pub fn make(stream: Stream) -> Self {
        CreateStreamRequest { stream }
    }
}

impl Default for CreateStreamRequest {
    fn default() -> CreateStreamRequest {
        CreateStreamRequest::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct CreateStreamResponse {
    pub created: String,
    error: Option<String>,
}

impl CreateStreamResponse {
    pub fn new() -> Self {
        CreateStreamResponse {
            created: Default::default(),
            error: None,
        }
    }

    pub fn make(created: String) -> Self {
        CreateStreamResponse {
            created,

            error: None,
        }
    }

    pub fn error(msg: String) -> Self {
        CreateStreamResponse {
            error: Some(msg),

            created: Default::default(),
        }
    }

    pub(crate) fn is_error(&self) -> bool {
        self.error != None
    }

    pub(crate) fn get_error(&self) -> Option<&String> {
        self.error.as_ref()
    }

    pub(crate) fn take_error(&mut self) -> Option<String> {
        self.error.take()
    }
}

impl Default for CreateStreamResponse {
    fn default() -> CreateStreamResponse {
        CreateStreamResponse::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct DeleteStreamRequest {
    pub name: String,
}

impl DeleteStreamRequest {
    pub fn new() -> Self {
        DeleteStreamRequest {
            name: Default::default(),
        }
    }

    pub fn make(name: String) -> Self {
        DeleteStreamRequest { name }
    }
}

impl Default for DeleteStreamRequest {
    fn default() -> DeleteStreamRequest {
        DeleteStreamRequest::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct DeleteStreamResponse {
    error: Option<String>,
}

impl DeleteStreamResponse {
    pub fn new() -> Self {
        DeleteStreamResponse { error: None }
    }

    pub fn make() -> Self {
        DeleteStreamResponse { error: None }
    }

    pub fn error(msg: String) -> Self {
        DeleteStreamResponse { error: Some(msg) }
    }

    pub(crate) fn is_error(&self) -> bool {
        self.error != None
    }

    pub(crate) fn get_error(&self) -> Option<&String> {
        self.error.as_ref()
    }

    pub(crate) fn take_error(&mut self) -> Option<String> {
        self.error.take()
    }
}

impl Default for DeleteStreamResponse {
    fn default() -> DeleteStreamResponse {
        DeleteStreamResponse::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct GetDeviceInfoRequest {}

impl GetDeviceInfoRequest {
    pub fn new() -> Self {
        GetDeviceInfoRequest {}
    }

    pub fn make() -> Self {
        GetDeviceInfoRequest {}
    }
}

impl Default for GetDeviceInfoRequest {
    fn default() -> GetDeviceInfoRequest {
        GetDeviceInfoRequest::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct ChannelInfo {
    pub sample_rates: i64,
    pub desc: String,
}

impl ChannelInfo {
    pub fn new() -> Self {
        ChannelInfo {
            sample_rates: Default::default(),
            desc: Default::default(),
        }
    }

    pub fn make(sample_rates: i64, desc: String) -> Self {
        ChannelInfo { sample_rates, desc }
    }
}

impl Default for ChannelInfo {
    fn default() -> ChannelInfo {
        ChannelInfo::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct DeviceInfo {
    pub channels: ChannelInfo,
}

impl DeviceInfo {
    pub fn new() -> Self {
        DeviceInfo {
            channels: Default::default(),
        }
    }

    pub fn make(channels: ChannelInfo) -> Self {
        DeviceInfo { channels }
    }
}

impl Default for DeviceInfo {
    fn default() -> DeviceInfo {
        DeviceInfo::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct GetDeviceInfoResponse {
    pub info: DeviceInfo,
    error: Option<String>,
}

impl GetDeviceInfoResponse {
    pub fn new() -> Self {
        GetDeviceInfoResponse {
            info: Default::default(),
            error: None,
        }
    }

    pub fn make(info: DeviceInfo) -> Self {
        GetDeviceInfoResponse { info, error: None }
    }

    pub fn error(msg: String) -> Self {
        GetDeviceInfoResponse {
            error: Some(msg),

            info: Default::default(),
        }
    }

    pub(crate) fn is_error(&self) -> bool {
        self.error != None
    }

    pub(crate) fn get_error(&self) -> Option<&String> {
        self.error.as_ref()
    }

    pub(crate) fn take_error(&mut self) -> Option<String> {
        self.error.take()
    }
}

impl Default for GetDeviceInfoResponse {
    fn default() -> GetDeviceInfoResponse {
        GetDeviceInfoResponse::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct ListStreamsRequest {}

impl ListStreamsRequest {
    pub fn new() -> Self {
        ListStreamsRequest {}
    }

    pub fn make() -> Self {
        ListStreamsRequest {}
    }
}

impl Default for ListStreamsRequest {
    fn default() -> ListStreamsRequest {
        ListStreamsRequest::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct StreamWithMetrics {
    pub stream: Stream,
    pub status: String,
    pub total_sent: i64,
    pub total_received: i64,
    pub created: String,
}

impl StreamWithMetrics {
    pub fn new() -> Self {
        StreamWithMetrics {
            stream: Default::default(),
            status: Default::default(),
            total_sent: Default::default(),
            total_received: Default::default(),
            created: Default::default(),
        }
    }

    pub fn make(
        stream: Stream,
        status: String,
        total_sent: i64,
        total_received: i64,
        created: String,
    ) -> Self {
        StreamWithMetrics {
            stream,

            status,

            total_sent,

            total_received,

            created,
        }
    }
}

impl Default for StreamWithMetrics {
    fn default() -> StreamWithMetrics {
        StreamWithMetrics::new()
    }
}

#[derive(Serialize, Deserialize)]
pub struct ListStreamsResponse {
    pub streams: StreamWithMetrics,
    error: Option<String>,
}

impl ListStreamsResponse {
    pub fn new() -> Self {
        ListStreamsResponse {
            streams: Default::default(),
            error: None,
        }
    }

    pub fn make(streams: StreamWithMetrics) -> Self {
        ListStreamsResponse {
            streams,

            error: None,
        }
    }

    pub fn error(msg: String) -> Self {
        ListStreamsResponse {
            error: Some(msg),

            streams: Default::default(),
        }
    }

    pub(crate) fn is_error(&self) -> bool {
        self.error != None
    }

    pub(crate) fn get_error(&self) -> Option<&String> {
        self.error.as_ref()
    }

    pub(crate) fn take_error(&mut self) -> Option<String> {
        self.error.take()
    }
}

impl Default for ListStreamsResponse {
    fn default() -> ListStreamsResponse {
        ListStreamsResponse::new()
    }
}

pub(crate) struct MockAudioInterface {
    error: Option<&'static str>,
}

impl MockAudioInterface {
    pub(crate) fn new() -> MockAudioInterface {
        MockAudioInterface { error: None }
    }

    pub(crate) fn error(message: &'static str) -> MockAudioInterface {
        MockAudioInterface {
            error: Some(message),
        }
    }
}

impl AudioInterface for MockAudioInterface {
    fn create_stream(&self, _: CreateStreamRequest) -> Result<CreateStreamResponse, String> {
        match self.error {
            Some(msg) => Err(String::from(msg)),
            None => Ok(Default::default()),
        }
    }

    fn delete_stream(&self, _: DeleteStreamRequest) -> Result<DeleteStreamResponse, String> {
        match self.error {
            Some(msg) => Err(String::from(msg)),
            None => Ok(Default::default()),
        }
    }

    fn get_device_info(&self, _: GetDeviceInfoRequest) -> Result<GetDeviceInfoResponse, String> {
        match self.error {
            Some(msg) => Err(String::from(msg)),
            None => Ok(Default::default()),
        }
    }

    fn list_streams(&self, _: ListStreamsRequest) -> Result<ListStreamsResponse, String> {
        match self.error {
            Some(msg) => Err(String::from(msg)),
            None => Ok(Default::default()),
        }
    }
}

#[cfg(test)]
mod test {
    use super::*;

    mod audio_interface {
        use super::super::*;

        #[test]
        fn test_create_stream_ok() {
            assert!(MockAudioInterface::new()
                .create_stream(Default::default())
                .is_ok());
        }

        #[test]
        #[should_panic]
        fn test_create_stream_error() {
            MockAudioInterface::error("quaranstream")
                .create_stream(Default::default())
                .expect("should panic because its an error");
        }

        #[test]
        fn test_delete_stream_ok() {
            assert!(MockAudioInterface::new()
                .delete_stream(Default::default())
                .is_ok());
        }

        #[test]
        #[should_panic]
        fn test_delete_stream_error() {
            MockAudioInterface::error("quaranstream")
                .delete_stream(Default::default())
                .expect("should panic because its an error");
        }

        #[test]
        fn test_get_device_info_ok() {
            assert!(MockAudioInterface::new()
                .get_device_info(Default::default())
                .is_ok());
        }

        #[test]
        #[should_panic]
        fn test_get_device_info_error() {
            MockAudioInterface::error("quaranstream")
                .get_device_info(Default::default())
                .expect("should panic because its an error");
        }

        #[test]
        fn test_list_streams_ok() {
            assert!(MockAudioInterface::new()
                .list_streams(Default::default())
                .is_ok());
        }

        #[test]
        #[should_panic]
        fn test_list_streams_error() {
            MockAudioInterface::error("quaranstream")
                .list_streams(Default::default())
                .expect("should panic because its an error");
        }
    }
}
