apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: audiounitclaims.app.paradise.dev
spec:
  group: app.paradise.dev
  names:
    kind: AudioUnitClaim
    listKind: AudioUnitClaimList
    plural: audiounitclaims
    singular: audiounitclaim
    shortNames:
      - auc
      - aucs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AudioUnitClaim is the Schema for the audiounitclaims API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AudioUnitClaimSpec defines the desired state of AudioUnitClaim
          type: object
        status:
          description: AudioUnitClaimStatus defines the observed state of AudioUnitClaim
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
