apiVersion: app.paradise.dev/v1alpha1
kind: AudioUnit
metadata:
  name: neve511
spec:
  manufacturer: "Rupert Neve Designs, LLC."

  # The number of input signals. Defaults to 1.
  inputs: 1

  # The number of output signals. Defaults to 1.
  outputs: 1
status:
  # If the unit is claimed, the status object will be
  # updated with details about its current ownership.
  # There could be multiple AudioUnitClaims attempting
  # to lay ownership to this resource, but only one
  # of them (shown here) will be the true owner.
  claim:
    name: neve511-test-claim
    timestamp: "2020-04-24T18:54:38Z"
---
apiVersion: app.paradise.dev/v1alpha1
kind: AudioUnitClaim
metadata:
  name: neve511-claim-0
  annotations:
  # For management and billing purposes, the claim can
  # be annotated with information about end user ownership.
    paradise.dev/owner: "6dc990b3-ce16-41ab-8952-41ffce9ebd95"
spec:
  # The name of the owning Console resource
  console: test-console

  # The name of the AudioUnit resource
  unit: neve511
status:
  # Pending
  # Active
  # Terminated
  # Expired
  # ErrMaxUnitsExceeded
  # ErrUnauthorized
  # ErrNoMoreUnits
  phase: Pending

  # The claim will automatically transition into
  # the Expired phase by this date if it is still
  # in the Active phase.
  expiration: "2020-04-24T18:54:38Z"

  # Physical patchbay, for analog signal routing.
  # All units must be connected to a patchbay for audio
  # signal routing. This one is MIDI programmable:
  # https://www.anatal.io/
  patchbay: pb0
---
# This patch utilizes analog-to-digital conversion
apiVersion: app.paradise.dev/v1alpha1
kind: Patch
metadata:
  name: test-output-patch
spec:
  source:
    unitClaim:
      name: my-ssl611eq-output
      channel: 0
  dest:
    remote:
      host: 297.281.23.1
      port: 35000
status:
  # ErrUnableToReconcile
  phase: Active
---
# This patch utilizes digital-to-analog conversion
apiVersion: app.paradise.dev/v1alpha1
kind: Patch
metadata:
  name: test-input-patch
spec:
  source:
    # Using a remote address as a patch source will
    # whitelist the port in the firewall, etc.
    remote:
      host: 297.281.23.1
      port: 35000
  dest:
    unitClaim:
      name: my-neve511-input
      channel: 0
---
# This patch is 100% analog
apiVersion: app.paradise.dev/v1alpha1
kind: Patch
metadata:
  name: test-pre-to-comp
spec:
  source:
    # Using a remote address as a patch source will
    # whitelist the port in the firewall, etc.
    unitClaim:
      name: my-neve511-claim
      channel: 0
  dest:
    unitClaim:
      name: my-comp-claim
      channel: 0
---
# This patch is 100% analog
apiVersion: app.paradise.dev/v1alpha1
kind: Patch
metadata:
  name: test-pre-to-comp
spec:
  source:
    unitClaim:
      name: my-comp-claim
      channel: 0
  dest:
    unitClaim:
      name: my-ssl611eq-output
      channel: 0
