---
# Cluster-scoped resource
apiVersion: app.paradise.dev/v1alpha1
kind: AudioUnitClass
metadata:
  name: neve511
spec:
  # TODO: think of other stuff to put here that could
  # be displayed in the VST plugin.
  displayName: "Neve Portico 511"

  # Manufacturer name. Displayed by the VST plugin.
  manufacturer: "Rupert Neve Designs, LLC."

  # Number of input signals. Defaults to 1.
  inputs: 1

  # Number of output signals. Defaults to 1.
  outputs: 1

  # Unit configuration. Corresponds to knobs and buttons
  # on the front of the unit.
  config:
    - name: trim
      smooth:
        min: -6
        max: 6
    - name: gain
      coarse:
        min: 0
        max: 66
        tick: 6
    - name: phantom_power
      toggle: {}
    - name: phase_invert
      toggle: {}
    - name: hpf
      smooth:
        min: 20
        max: 250
    - name: hpf_enabled
      toggle: {}
    - name: texture
      smooth:
        min: 0
        max: 100
    - name: silk_enabled
      toggle: {}
---
# Namespaced resource for managing individual analog hardware
# components. Each component will have fully analog I/O on
# a patchbay, which can be used to route the signal anywhere.
apiVersion: app.paradise.dev/v1alpha1
kind: AudioUnit
metadata:
  name: my-neve511-0
  namespace: default

  # Uniquely identifies the unit between clusters. This is
  # necessary because an AudioUnitClaim may be created in
  # a cluster other than the one servicing the AudioUnits,
  # as is the case with PersistenceVolume/PersistenceVolumeClaim.
  uid: "6dc990b3-ce16-41ab-8952-41ffce9ebd95"

  # Audio unit driver endpoint. Used to to retrieve device info,
  # send/receive audio, perform automation, etc...
  # All audio units that are configurable in any way have an
  # endpoint associated with them. This is considered a mandatory
  # field. It does not have to be unique to the device, as the
  # datagram can contain that information. Note that this endpoint
  # *not* be able to receive the audio stream, as is the case
  # with analog units. Analog units must receive audio from a patch.
  endpoint: io1.quantum.svc.cluster.local:4000

spec:
  # Allow this unit to be reserved by claims requesting
  # units with the same name. There must be a corresponding
  # AudioUnitClass with this name
  className: neve511

  # Name of the patchbay servicing I/O for the unit.
  patchbay:
    # Globally unique serial number for the particular patchbay.
    uid: "602898e4-fe9f-424d-9a31-275c5e26023a"

    outputs:  # Output channels reserved on patchbay
      - 83    # OUTPUT 83 of the patchbay -> first (only) input of unit
    inputs:   # Input channels reserved on patchbay
      - 34    # First (only) output of unit -> INPUT 34 of patchbay
---
apiVersion: app.paradise.dev/v1alpha1
kind: AudioUnitClaim
metadata:
  name: neve511-claim-0
spec:
  # Name of the corresponding AudioUnitClass in the backend.
  className: neve511

  # Define overrides for the unit's configuration. As these
  # are changed on the kubernetes API server, automation
  # reconciles any differences with the physical unit.
  config:
    - name: gain
      value: 12
    - name: silk_enabled
      value: true

status:
  # Pending
  # Active
  # Terminated
  # Expired
  # ErrMaxUnitsExceeded
  # ErrUnauthorized
  # ErrNoMoreUnits
  phase: Pending

  # Globally identifying hardware SKU.
  # There is a corresponding AudioUnit.metadata.uid that
  # unambiguously refers to a particular physical unit.
  uid: "6dc990b3-ce16-41ab-8952-41ffce9ebd95"

  # The claim will automatically transition into
  # the Expired phase by this date if it is still
  # in the Active phase.
  expiration: "2020-04-24T18:54:38Z"
---
# This patch utilizes analog-to-digital conversion.
# It is created on a cluster and causes network/hardware
# resources to be appropriately reconciled by the backend.
apiVersion: app.paradise.dev/v1alpha1
kind: Patch
metadata:
  name: test-output-patch
spec:
  source:
    name: my-ssl611eq-claim
    channel: 0
  dest:
    name: my-audio-interface-claim
    channel: 0
status:
  # ErrUnableToReconcile
  phase: Active
---
# This patch utilizes digital-to-analog conversion.
# It is anticipated that any patch involving a digital
# signal will have a low infrastructure footprint due
# to thorough distribution of audio interfaces across
# the cluster of patchbays.
apiVersion: app.paradise.dev/v1alpha1
kind: Patch
metadata:
  name: test-input-patch
spec:
  source:
    name: my-audio-interface-claim
    channel: 3
  dest:
    name: my-neve511-claim
    # You can patch to a unit in a different namespace.
    # By default, it's assumed the unit is in the same
    # namespace as the patch.
    namespace: some-other-namespace
    channel: 0
status:
  phase: Active
---
# This patch is 100% analog. It is still possible that
# users request impossible situations due to inefficient
# analog routing.
apiVersion: app.paradise.dev/v1alpha1
kind: Patch
metadata:
  name: test-pre-to-comp
spec:
  source:
    name: my-neve511-claim
    channel: 0 # Output
  dest:
    name: my-comp-claim
    channel: 0 # Input
status:
  phase: Active
---
apiVersion: app.paradise.dev/v1alpha1
kind: Patch
metadata:
  name: test-pre-to-comp
spec:
  source:
    name: my-comp-claim
    channel: 0
  dest:
    name: my-ssl611eq-claim
    channel: 0
status:
  phase: Active
